tap "eddieantonio/eddieantonio"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/science"
brew "gdbm"
brew "sqlite"
brew "python"
brew "ansible"
brew "autoconf"
brew "automake"
brew "awscli"
brew "awslogs"
brew "caddy"
brew "fontconfig"
brew "calc"
brew "cloc"
brew "cloog"
brew "coreutils"
brew "cpanminus"
brew "curl"
brew "go"
brew "dep"
brew "diff-so-fancy"
brew "doxygen"
brew "emacs"
brew "exiftool"
brew "lame"
brew "x264"
brew "xvid"
brew "ffmpeg"
brew "fftw"
brew "fio"
brew "gcc@4.9"
brew "gdk-pixbuf"
brew "giflib"
brew "gifsicle"
brew "git"
brew "gnupg"
brew "gnuplot"
brew "graphicsmagick"
brew "htop"
brew "httpie"
brew "imagemagick"
brew "jq"
brew "libcroco"
brew "libexif"
brew "libgsf"
brew "librsvg"
brew "libvo-aacenc"
brew "lz4"
brew "mas"
brew "mtr"
brew "n"
brew "nmap"
brew "orc"
brew "pngcrush"
brew "poppler"
brew "pre-commit"
brew "psutils"
brew "pv"
brew "py2cairo"
brew "pyenv"
brew "pyenv-virtualenv"
brew "rclone"
brew "rename"
brew "rsync"
brew "ruby", link: true
brew "ruby-build"
brew "s3cmd"
brew "shared-mime-info"
brew "terraform"
brew "tre"
brew "tree"
brew "vips"
brew "watch"
brew "watchman"
brew "wget"
brew "yarn"
brew "eddieantonio/eddieantonio/imgcat"
cask "docker"
cask "dropbox"
cask "flux"
cask "google-chrome"
cask "google-cloud-sdk"
cask "insomniax"
cask "java8"
cask "macdown"
cask "shiftit"
cask "spotify"
cask "visual-studio-code"
mas "1Password 7 - Password Manager", id: 1333542190
mas "Alfred", id: 405843582
mas "Bear", id: 1091189122
mas "BetterSnapTool", id: 417375580
mas "ColorSlurp", id: 1287239339
mas "Monosnap", id: 540348655
mas "Paw", id: 584653203
mas "Slack", id: 803453959
mas "Spark", id: 1176895641
mas "Tweetbot", id: 557168941
mas "Xcode", id: 497799835
