tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "calc"
brew "diff-so-fancy"
brew "emacs"
brew "fzf"
brew "git"
brew "httpie"
brew "jq"
brew "mas"
brew "nmap"
brew "tree"
brew "virtualenvwrapper"
brew "wget"
brew "yarn"
cask "discord"
cask "flux"
cask "iterm2"
cask "slack"
cask "spotify"
cask "visual-studio-code"
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
